test: place path card test 5
Game-as-a-Service/saboteur-remix pull request #35
Opened 2023-04-23 04:24 UTC by nana-yang-hy

complete test: place path card test 5

2023-04-23 07:46 UTC, kayac-chang requested changes

2023-04-23 07:46 UTC, kayac-chang commented on apps/backend/src/board/logic/place-path-card.test.ts
> +    placePathCard(
@nana-yang-hy 
In this scenario, by reference 
```
    given:
      a board with
        - a start card at position (0, 0)
```
we want to **place the a start card at position (0, 0)** first, 
先放 一張 start card 在 position (0, 0)

after that, then place **path card [connected cross] at position (0, 1)**
接著，再放 path card [connected cross] 在 position (0, 1)

2023-04-28 06:52 UTC, nana-yang-hy commented on apps/backend/src/board/logic/place-path-card.test.ts
> +    placePathCard(
@kayac-chang 
再次修改好test內容，再麻煩確認，感謝～

2023-04-29 06:46 UTC, kayac-chang approved these changes
LGTM

2023-04-29 06:46 UTC, kayac-chang commented on apps/backend/src/board/logic/place-path-card.test.ts
> +    placePathCard(
LGTM

2023-04-29 06:47 UTC, merged