Update Issue [implement place path card test and logic 4]
Game-as-a-Service/saboteur-remix pull request #43
Opened 2023-04-23 08:29 UTC by MatthewNoah4132

2023-04-23 09:07 UTC, kayac-chang requested changes

2023-04-23 09:07 UTC, kayac-chang commented on apps/backend/src/board/logic/place-path-card.test.ts
> +      .then(() =>
換 `andThen`，
參考 https://github.com/supermacro/neverthrow#resultandthen-method

2023-04-23 09:12 UTC, kayac-chang commented
@MatthewNoah4132 
FYI, 
- 你要先跑 code format 在上傳之前，`yarn format` 會幫你跑過 format。
- 這個測試要調整一下

```diff
    given:
      a board with
        - a start card at position (0, 0)
        - a path card [connected top left right] at position (1, 0)
    when:
      place
        a path card [connected left bottom] at position (2, 0)
    then:
      - should return
        - path card has been placed event with
          - path card [connected left bottom] at position (2, 0)
      - event source should includes
        - path card has been placed event with
          - a start card at position (0, 0)
+         - a path card [connected top left right] at position (1, 0)
+         - path card [connected left bottom] at position (2, 0)
```

2023-04-23 13:03 UTC, MatthewNoah4132 commented on apps/backend/src/board/logic/place-path-card.test.ts
> +      .then(() =>
Thanks, @kayac-chang

2023-04-28 04:07 UTC, kayac-chang commented
> @kayac-chang 請問- event source should includes為什麼要多這兩行呢? 而- should return不用多這兩行呢?
> 
> * a start card at position (0, 0)
> * a path card [connected top left right] at position (1, 0)
> * path card [connected left bottom] at position (2, 0) 這一行原本就有
> 
> 我的理解是
> 
> * should return是這個unit test的結果，所以只需要- path card [connected left bottom] at position (2, 0) 這一行
> * event source should includes像資料庫，紀錄given, when, then後的整個狀態，所以需要多那兩行
> 
> 不知道以上理解是否正確，sorry, 還有蠻多地方沒有搞懂的

`place path card` 函式的設計是這樣：
`輸入 command => place path card => 輸出對應的 event`
它 return 的是當前這個 `command` 所對應 `event`。

```
place
        a path card [connected left bottom] at position (2, 0)
```

是給與 一個 place path command 並且它附帶的資訊是
- 卡片是 [connected left bottom]
- 放置的位置 (2, 0)
而其對應的 event 就是，上面這個 command 被執行後所觸發的事件。

而 event source，你可以想成是 **這個遊戲中所有的事件的紀錄**，
所以前面的情境，
```
      a board with
        - a start card at position (0, 0)
        - a path card [connected top left right] at position (1, 0)
```
表示 event source 一定已經有這兩個事件先發生了，
> 你的桌上已經先放置這兩張卡片了。

所以，我預期的 event source 應該要有至少三個事件

- 放置 start card at position (0, 0) 事件
- 放置 path card [connected top left right] at position (1, 0) 的事件
- 放置 path card [connected left bottom] at position (2, 0) 的事件

2023-04-30 06:26 UTC, kayac-chang commented
Try to closed: #28

2023-05-14 06:07 UTC, kayac-chang approved these changes
LGTM

2023-05-14 06:08 UTC, merged