feat: add todo test and todo logic
Game-as-a-Service/saboteur-remix pull request #62
Opened 2023-04-30 16:57 UTC by Dlutermade

先添加好 Todo Test 和 Todo Logic

目前可能需要的 Logic
1. get emit event player hands (取得發出事件玩家手牌) 
1.1. 用於判斷使用者 是否必須 棄牌
1.2. 用於判斷使用者 棄掉的牌 是否出於 玩家手中
2. get current deck ( 取得當前牌組 ) ( 也可能不需要 移出給別的event來負責)
2.2.  判斷是否可以給 player 進行補牌

2023-05-03 05:05 UTC, kayac-chang requested changes

2023-05-03 05:05 UTC, kayac-chang commented on apps/backend/src/action/logic/pass.ts
> +   **/
God Job!!!
Try to use English, and don't be afraid to make mistakes.

You can also consider using ChatGPT or Grammarly to check your sentence.
This definitely helps.

2023-05-03 05:55 UTC, Dlutermade commented on apps/backend/src/action/command/pass.command.ts
> +export function PassCommand(card: PathCard | null): PassCommand {
我當時也在想要用 null 還是 ? 還是undefined

2023-05-03 06:03 UTC, Dlutermade commented on apps/backend/src/action/logic/pass.test.ts
> +   * 因此到時候可能移除
LAMO，I forgot to remove

2023-05-03 06:20 UTC, Dlutermade commented on apps/backend/src/action/command/pass.command.ts
> +    card: z.nativeEnum(PathCard).nullable(),
if use  `nullish` 
should we update  `card: PathCard | null` to  `card?: PathCard | null`

2023-05-04 08:35 UTC, kayac-chang commented on apps/backend/src/action/command/pass.command.ts
> +export function PassCommand(card: PathCard | null): PassCommand {
LGTM

2023-05-04 08:38 UTC, kayac-chang commented on apps/backend/src/action/command/pass.command.ts
> +    card: z.nativeEnum(PathCard).nullable(),
By using `nullish` which can handle both scenario `null` or `undefined`.

2023-05-04 08:38 UTC, kayac-chang commented on apps/backend/src/action/command/pass.command.ts
> +    card: z.nativeEnum(PathCard).nullable(),
LGTM

2023-05-04 08:38 UTC, kayac-chang commented on apps/backend/src/action/event/turn-has-been-passed.event.ts
> +  discardCard: PathCard | null
LGTM

2023-05-04 08:39 UTC, kayac-chang commented on apps/backend/src/action/event/turn-has-been-passed.event.ts
> +    discardCard: z.nativeEnum(PathCard).nullable(),
LGTM

2023-05-04 08:39 UTC, kayac-chang commented on apps/backend/src/action/logic/pass.test.ts
> +   * 因此到時候可能移除
LGTM

2023-05-04 08:40 UTC, kayac-chang approved these changes
LGTM

2023-05-04 08:40 UTC, merged